[package]
name = "binaural_8d_audio"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
hrtf = "0.8.1"
biquad = "0.5"
freeverb = "0.1"
hound = "3.5.1"
symphonia = { version = "0.5.5", features = ["all"] }
rubato = "0.16.2"
flacenc = "0.5"
mp3lame-encoder = "0.2.1"
rodio = "0.21.1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[[bin]]
name = "make8d"
path = "src/main.rs"
